/**
 * Conventional Commits validation for the commits in a pull request.
 *
 * The repo convention (openspec/project.md) requires Conventional Commits and
 * forbids AI attribution / Co-Authored-By trailers. This is a dependency-free
 * validator so CI needs no new package or lockfile churn.
 */

/** Conventional-Commits types accepted in this repo's history. */
export const CONVENTIONAL_TYPES = [
  'feat',
  'fix',
  'docs',
  'style',
  'refactor',
  'perf',
  'test',
  'build',
  'ci',
  'chore',
  'revert',
] as const

const SUBJECT_RE = new RegExp(`^(?:${CONVENTIONAL_TYPES.join('|')})(?:\\([^)]+\\))?!?: .+`)

const AI_ATTRIBUTION_RE =
  /^co-authored-by:\s*.*(claude|anthropic|openai|chatgpt|gpt-?\d|copilot|cursor|codex|gemini|bard|devin|aider|windsurf|codeium|continue\.dev)/im

/** Return a list of human-readable problems; an empty list means the message is valid. */
export function validateCommitMessage(message: string): string[] {
  const errors: string[] = []
  const lines = message.split('\n')
  const subject = (lines.find((l) => l.trim().length > 0) ?? '').trim()

  // Merge commits are generated by git, not authored, and carry no type.
  if (!/^Merge /.test(subject)) {
    if (!SUBJECT_RE.test(subject)) {
      errors.push(
        `subject does not follow Conventional Commits ("type(scope): summary"): "${subject}"`,
      )
    }
  }

  const ai = message.match(AI_ATTRIBUTION_RE)
  if (ai) {
    errors.push(`AI attribution is not allowed: "${ai[0].trim()}"`)
  }

  return errors
}
